### ISSUE TITLE
Method declared in namespace; should be part of a class

### ISSUE THREAD

**Issue by eflumerf** [Mu2e/artdaq_core_mu2e#23]
https://github.com/Mu2e/artdaq_core_mu2e/blob/bf181de55232678cb230dd682ea3af20d5e49ddd/artdaq-core-mu2e/Overlays/DTC_Types.h#L120

e.g. struct Utilities declared at the end of the file

**Comment by rrivera747** [comment]
Resolved in https://github.com/Mu2e/artdaq_core_mu2e/pull/28
